<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Backgrounds\cd.gif" />
    <None Remove="Backgrounds\SoundButton.png" />
    <None Remove="Backgrounds\Угадай мелодию интро.png" />
    <None Remove="Backgrounds\Фон угадывания мелодии.jpg" />
    <None Remove="Media\Андрей Губин - Такие девушки как звезды %28минус%29.mp3" />
    <None Remove="Media\Андрей Губин - Такие девушки как звезды.mp3" />
    <None Remove="Media\Андрей Губин - Такие девушки как звезды.mp4" />
    <None Remove="Media\Мария Пахоменко - Стоят Девчонки %28минус%29.mp3" />
    <None Remove="Media\Мария Пахоменко - Стоят Девчонки.mp3" />
    <None Remove="Media\Мария Пахоменко - Стоят девчонки.mp4" />
    <None Remove="Media\Муслим Магомаев - Королева красоты %28минус%29.mp3" />
    <None Remove="Media\Муслим Магомаев - Королева красоты.mp3" />
    <None Remove="Media\Муслим Магомаев - Королева красоты.mp4" />
    <None Remove="Media\Полина Гагарина - Спектакль окончен.mp4" />
    <None Remove="Resources\opening2013.wav" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Media\Андрей Губин - Такие девушки как звезды (минус).mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Media\Андрей Губин - Такие девушки как звезды.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Media\Андрей Губин - Такие девушки как звезды.mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Media\Мария Пахоменко - Стоят Девчонки (минус).mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Media\Мария Пахоменко - Стоят Девчонки.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Media\Мария Пахоменко - Стоят девчонки.mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Media\Муслим Магомаев - Королева красоты (минус).mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Media\Муслим Магомаев - Королева красоты.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Media\Муслим Магомаев - Королева красоты.mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Media\Полина Гагарина - Спектакль окончен.mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\opening2013.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Backgrounds\cd.gif" />
    <Resource Include="Backgrounds\SoundButton.png" />
    <Resource Include="Backgrounds\Угадай мелодию интро.png" />
    <Resource Include="Backgrounds\Фон угадывания мелодии.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
